customhost = "database-1.csyu0w9pvnji.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leeyunkai-employee"
customregion = "us-east-1"
